<a href="https://colab.research.google.com/github/YJInn0121/QM2-Group-Project/blob/main/data_cleaning_gcse_results.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded=files.upload()
! pip install pandas
import pandas as pd
df = pd.read_excel("gcse-results-old.xls",header=1)
df

Saving gcse-results-old.xls to gcse-results-old (9).xls
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

,Code,Area,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,Unnamed: 8,2009/10.1,2010/11.1,2011/12.1,2012/13.1,2013/14.1,2014/15.1
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E09000001,City of London,.,.,.,.,.,.,NaN,.,.,.,.,.,.
2,E09000002,Barking and Dagenham,51.6,57.2,58.6,60.2,58.2,54,NaN,76.5,81.2,83.3,82.5,65.5,66.4
3,E09000003,Barnet,67.3,68.8,69.2,71.5,67.5,70.1,NaN,83.2,87,85.6,87,75.4,78.1
4,E09000004,Bexley,59.8,63.3,64.9,66,60.3,55,NaN,81.1,87.3,89.4,88.6,69.4,70.8
5,E09000005,Brent,60.1,62.1,58.7,62.9,60,60,NaN,75.4,79.9,77.7,81.1,69.3,70.6
6,E09000006,Bromley,65.1,67.2,68.9,73.9,65.6,68,NaN,85.2,88.1,93.2,92.9,74.5,74.8
7,E09000007,Camden,53.1,60.2,59,60.4,60.5,56.4,NaN,68.7,73.7,77.3,77.5,68.2,67.8
8,E09000008,Croydon,54.4,61,62.2,64.4,56.8,59.6,NaN,82.9,87.4,88,85.3,68.1,69.6
9,E09000009,Ealing,58.7,57.3,57.7,60.9,59.8,62.1,NaN,76.9,76.2,78.8,80,67.9,69.7
10,E09000010,Enfield,55.3,59.5,55.5,63.2,59.7,54.5,NaN,74.1,81.2,81.1,81,68.5,65.2
11,E09000011,Greenwich,50.1,54.5,63.1,65.4,59.6,57.7,NaN,72,75.6,88.6,89.6,70.5,69.3
12,E09000012,Hackney,55.3,57,60.2,61.2,58.8,60.4,NaN,71.1,74.9,79.2,79.6,71.1,69.7
13,E09000013,Hammersmith and Fulham,68.2,71.3,65.6,66.5,65.6,62.6,NaN,89.1,91.5,83.8,83.5,73.6,73.6
14,E09000014,Haringey,48,57.3,58.6,63.5,59.1,54.6,NaN,73,77.6,78.8,83.5,69.8,65.5
15,E09000015,Harrow,60.7,64.6,63.6,65.4,62.3,60.5,NaN,78.1,80.3,83.8,82.2,71.3,73.2
16,E09000016,Havering,62.3,63.9,61.5,63.7,60.2,57.7,NaN,77.4,79.6,81.4,79.1,68.6,66.4
17,E09000017,Hillingdon,55.8,59.5,61,61.6,58.6,57.5,NaN,80.7,84.9,86.6,87.2,68.3,68
18,E09000018,Hounslow,58.7,62.5,61.8,66.7,66.1,65.2,NaN,82.4,86.8,88.1,86.8,74.4,75.5
19,E09000019,Islington,50,49.4,53.6,63.5,59.9,57.9,NaN,72,75.1,78.8,82.9,69.5,69.1
20,E09000020,Kensington and Chelsea,71.3,73.1,79.6,80.2,73.8,67.2,NaN,92.4,91,89.6,92.1,79.4,76.6
21,E09000021,Kingston upon Thames,68.7,71,70.1,71.6,70,73.2,NaN,83.3,87.3,87.7,87,78.3,80.6
22,E09000022,Lambeth,53,61.1,62.8,65.9,57,56.5,NaN,74.2,80.1,85,86.4,68.2,67.5
23,E09000023,Lewisham,48,55.9,55.6,58,51.3,51.9,NaN,64,68.8,74.6,79,59,62.3
24,E09000024,Merton,52.4,59.8,59.1,62.6,64.2,60,NaN,77.1,85.8,84.6,85.6,70.8,70.5
25,E09000025,Newham,52.1,58.5,61.9,58.4,55.4,59.4,NaN,69.2,75.7,79.4,79.1,66,70.8
26,E09000026,Redbridge,69.3,68.5,70.6,70.2,68.1,63.4,NaN,81.2,81.8,87,86.8,77.1,75.5
27,E09000027,Richmond upon Thames,61.4,63.2,62.6,68.3,63.5,64.7,NaN,79.3,81.8,84,85.9,73.8,74
28,E09000028,Southwark,56.1,58,58.8,65.2,62.4,64.3,NaN,78.9,81.7,84.8,85.1,71.3,73.6
29,E09000029,Sutton,70.6,74.7,75.9,77,72.1,70.4,NaN,88.9,91.7,93.2,91.7,80.2,81
30,E09000030,Tower Hamlets,51.8,61.4,61.8,64.7,59.7,64.6,NaN,74.9,80.8,84.3,85.8,69.2,73.4
31,E09000031,Waltham Forest,50.9,54.3,52.6,56.7,56.7,57.4,NaN,66.6,77.2,77,78.6,66,67.9
32,E09000032,Wandsworth,58.1,61.7,58.3,61.3,59.1,58.2,NaN,79.7,84.6,85.4,83,66.8,67.9
33,E09000033,Westminster,62.5,63.1,69.9,69.6,68.1,67.5,NaN,83.9,85.9,87.5,86.8,76.8,77.5
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,E13000001,Inner London,54.2,59.6,60.8,63.1,59.5,59.7,NaN,74.4,78.9,81.6,82.8,68.9,70
36,E13000002,Outer London,59.8,62.9,63.1,66,62.4,61.4,NaN,79.3,83.4,85.3,85.2,71.3,71.8
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,E12000001,North East,52.8,56.8,58.5,59.3,54.6,55.4,NaN,79.5,84.7,88,87.9,63.3,64.9
39,E12000002,North West,55.2,58.4,58.9,59.9,55.8,55.9,NaN,77.7,82.2,84.2,83.5,65.4,66
40,E12000003,Yorkshire and the Humber,52,54.6,57.3,59.5,53.9,55.1,NaN,76.7,81.5,84.1,84.7,62.8,63.8
41,E12000004,East Midlands,53.7,57.1,57.6,59.3,54,54.2,NaN,75.2,80,82.7,82.8,63.1,63
42,E12000005,West Midlands,54.2,57.4,58.8,59.9,54.9,55.1,NaN,77.9,83,85.5,85.6,64.2,64.4
43,E12000006,East,56,59.1,58.2,59.8,57.2,58.2,NaN,74.3,78,80.6,79.6,65.5,66.7
44,E12000007,London,58,61.9,62.3,65.1,61.5,60.9,NaN,77.8,82,84.1,84.4,70.5,71.2
45,E12000008,South East,57.5,59.6,60.2,62.5,59,59.9,NaN,75.7,79.3,82,82.4,67.4,67.9
46,E12000009,South West,55.4,57.9,57.5,59.5,56.7,58,NaN,72.7,76.8,79.8,79.8,66.2,66.9
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,E92000001,England,53.4,58.4,59.4,59.2,53.4,53.8,NaN,75.4,80.7,81.8,81.8,63.8,64.9

In [ ]:
df.dropna(how='all', inplace=True)
df

,Code,Area,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,Unnamed: 8,2009/10.1,2010/11.1,2011/12.1,2012/13.1,2013/14.1,2014/15.1
1,E09000001,City of London,.,.,.,.,.,.,NaN,.,.,.,.,.,.
2,E09000002,Barking and Dagenham,51.6,57.2,58.6,60.2,58.2,54,NaN,76.5,81.2,83.3,82.5,65.5,66.4
3,E09000003,Barnet,67.3,68.8,69.2,71.5,67.5,70.1,NaN,83.2,87,85.6,87,75.4,78.1
4,E09000004,Bexley,59.8,63.3,64.9,66,60.3,55,NaN,81.1,87.3,89.4,88.6,69.4,70.8
5,E09000005,Brent,60.1,62.1,58.7,62.9,60,60,NaN,75.4,79.9,77.7,81.1,69.3,70.6
6,E09000006,Bromley,65.1,67.2,68.9,73.9,65.6,68,NaN,85.2,88.1,93.2,92.9,74.5,74.8
7,E09000007,Camden,53.1,60.2,59,60.4,60.5,56.4,NaN,68.7,73.7,77.3,77.5,68.2,67.8
8,E09000008,Croydon,54.4,61,62.2,64.4,56.8,59.6,NaN,82.9,87.4,88,85.3,68.1,69.6
9,E09000009,Ealing,58.7,57.3,57.7,60.9,59.8,62.1,NaN,76.9,76.2,78.8,80,67.9,69.7
10,E09000010,Enfield,55.3,59.5,55.5,63.2,59.7,54.5,NaN,74.1,81.2,81.1,81,68.5,65.2
11,E09000011,Greenwich,50.1,54.5,63.1,65.4,59.6,57.7,NaN,72,75.6,88.6,89.6,70.5,69.3
12,E09000012,Hackney,55.3,57,60.2,61.2,58.8,60.4,NaN,71.1,74.9,79.2,79.6,71.1,69.7
13,E09000013,Hammersmith and Fulham,68.2,71.3,65.6,66.5,65.6,62.6,NaN,89.1,91.5,83.8,83.5,73.6,73.6
14,E09000014,Haringey,48,57.3,58.6,63.5,59.1,54.6,NaN,73,77.6,78.8,83.5,69.8,65.5
15,E09000015,Harrow,60.7,64.6,63.6,65.4,62.3,60.5,NaN,78.1,80.3,83.8,82.2,71.3,73.2
16,E09000016,Havering,62.3,63.9,61.5,63.7,60.2,57.7,NaN,77.4,79.6,81.4,79.1,68.6,66.4
17,E09000017,Hillingdon,55.8,59.5,61,61.6,58.6,57.5,NaN,80.7,84.9,86.6,87.2,68.3,68
18,E09000018,Hounslow,58.7,62.5,61.8,66.7,66.1,65.2,NaN,82.4,86.8,88.1,86.8,74.4,75.5
19,E09000019,Islington,50,49.4,53.6,63.5,59.9,57.9,NaN,72,75.1,78.8,82.9,69.5,69.1
20,E09000020,Kensington and Chelsea,71.3,73.1,79.6,80.2,73.8,67.2,NaN,92.4,91,89.6,92.1,79.4,76.6
21,E09000021,Kingston upon Thames,68.7,71,70.1,71.6,70,73.2,NaN,83.3,87.3,87.7,87,78.3,80.6
22,E09000022,Lambeth,53,61.1,62.8,65.9,57,56.5,NaN,74.2,80.1,85,86.4,68.2,67.5
23,E09000023,Lewisham,48,55.9,55.6,58,51.3,51.9,NaN,64,68.8,74.6,79,59,62.3
24,E09000024,Merton,52.4,59.8,59.1,62.6,64.2,60,NaN,77.1,85.8,84.6,85.6,70.8,70.5
25,E09000025,Newham,52.1,58.5,61.9,58.4,55.4,59.4,NaN,69.2,75.7,79.4,79.1,66,70.8
26,E09000026,Redbridge,69.3,68.5,70.6,70.2,68.1,63.4,NaN,81.2,81.8,87,86.8,77.1,75.5
27,E09000027,Richmond upon Thames,61.4,63.2,62.6,68.3,63.5,64.7,NaN,79.3,81.8,84,85.9,73.8,74
28,E09000028,Southwark,56.1,58,58.8,65.2,62.4,64.3,NaN,78.9,81.7,84.8,85.1,71.3,73.6
29,E09000029,Sutton,70.6,74.7,75.9,77,72.1,70.4,NaN,88.9,91.7,93.2,91.7,80.2,81
30,E09000030,Tower Hamlets,51.8,61.4,61.8,64.7,59.7,64.6,NaN,74.9,80.8,84.3,85.8,69.2,73.4
31,E09000031,Waltham Forest,50.9,54.3,52.6,56.7,56.7,57.4,NaN,66.6,77.2,77,78.6,66,67.9
32,E09000032,Wandsworth,58.1,61.7,58.3,61.3,59.1,58.2,NaN,79.7,84.6,85.4,83,66.8,67.9
33,E09000033,Westminster,62.5,63.1,69.9,69.6,68.1,67.5,NaN,83.9,85.9,87.5,86.8,76.8,77.5
35,E13000001,Inner London,54.2,59.6,60.8,63.1,59.5,59.7,NaN,74.4,78.9,81.6,82.8,68.9,70
36,E13000002,Outer London,59.8,62.9,63.1,66,62.4,61.4,NaN,79.3,83.4,85.3,85.2,71.3,71.8
38,E12000001,North East,52.8,56.8,58.5,59.3,54.6,55.4,NaN,79.5,84.7,88,87.9,63.3,64.9
39,E12000002,North West,55.2,58.4,58.9,59.9,55.8,55.9,NaN,77.7,82.2,84.2,83.5,65.4,66
40,E12000003,Yorkshire and the Humber,52,54.6,57.3,59.5,53.9,55.1,NaN,76.7,81.5,84.1,84.7,62.8,63.8
41,E12000004,East Midlands,53.7,57.1,57.6,59.3,54,54.2,NaN,75.2,80,82.7,82.8,63.1,63
42,E12000005,West Midlands,54.2,57.4,58.8,59.9,54.9,55.1,NaN,77.9,83,85.5,85.6,64.2,64.4
43,E12000006,East,56,59.1,58.2,59.8,57.2,58.2,NaN,74.3,78,80.6,79.6,65.5,66.7
44,E12000007,London,58,61.9,62.3,65.1,61.5,60.9,NaN,77.8,82,84.1,84.4,70.5,71.2
45,E12000008,South East,57.5,59.6,60.2,62.5,59,59.9,NaN,75.7,79.3,82,82.4,67.4,67.9
46,E12000009,South West,55.4,57.9,57.5,59.5,56.7,58,NaN,72.7,76.8,79.8,79.8,66.2,66.9
48,E92000001,England,53.4,58.4,59.4,59.2,53.4,53.8,NaN,75.4,80.7,81.8,81.8,63.8,64.9

In [ ]:
df.drop(df.index[33:50], inplace=True)
df

,Code,Area,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,Unnamed: 8,2009/10.1,2010/11.1,2011/12.1,2012/13.1,2013/14.1,2014/15.1
1,E09000001,City of London,.,.,.,.,.,.,NaN,.,.,.,.,.,.
2,E09000002,Barking and Dagenham,51.6,57.2,58.6,60.2,58.2,54,NaN,76.5,81.2,83.3,82.5,65.5,66.4
3,E09000003,Barnet,67.3,68.8,69.2,71.5,67.5,70.1,NaN,83.2,87,85.6,87,75.4,78.1
4,E09000004,Bexley,59.8,63.3,64.9,66,60.3,55,NaN,81.1,87.3,89.4,88.6,69.4,70.8
5,E09000005,Brent,60.1,62.1,58.7,62.9,60,60,NaN,75.4,79.9,77.7,81.1,69.3,70.6
6,E09000006,Bromley,65.1,67.2,68.9,73.9,65.6,68,NaN,85.2,88.1,93.2,92.9,74.5,74.8
7,E09000007,Camden,53.1,60.2,59,60.4,60.5,56.4,NaN,68.7,73.7,77.3,77.5,68.2,67.8
8,E09000008,Croydon,54.4,61,62.2,64.4,56.8,59.6,NaN,82.9,87.4,88,85.3,68.1,69.6
9,E09000009,Ealing,58.7,57.3,57.7,60.9,59.8,62.1,NaN,76.9,76.2,78.8,80,67.9,69.7
10,E09000010,Enfield,55.3,59.5,55.5,63.2,59.7,54.5,NaN,74.1,81.2,81.1,81,68.5,65.2
11,E09000011,Greenwich,50.1,54.5,63.1,65.4,59.6,57.7,NaN,72,75.6,88.6,89.6,70.5,69.3
12,E09000012,Hackney,55.3,57,60.2,61.2,58.8,60.4,NaN,71.1,74.9,79.2,79.6,71.1,69.7
13,E09000013,Hammersmith and Fulham,68.2,71.3,65.6,66.5,65.6,62.6,NaN,89.1,91.5,83.8,83.5,73.6,73.6
14,E09000014,Haringey,48,57.3,58.6,63.5,59.1,54.6,NaN,73,77.6,78.8,83.5,69.8,65.5
15,E09000015,Harrow,60.7,64.6,63.6,65.4,62.3,60.5,NaN,78.1,80.3,83.8,82.2,71.3,73.2
16,E09000016,Havering,62.3,63.9,61.5,63.7,60.2,57.7,NaN,77.4,79.6,81.4,79.1,68.6,66.4
17,E09000017,Hillingdon,55.8,59.5,61,61.6,58.6,57.5,NaN,80.7,84.9,86.6,87.2,68.3,68
18,E09000018,Hounslow,58.7,62.5,61.8,66.7,66.1,65.2,NaN,82.4,86.8,88.1,86.8,74.4,75.5
19,E09000019,Islington,50,49.4,53.6,63.5,59.9,57.9,NaN,72,75.1,78.8,82.9,69.5,69.1
20,E09000020,Kensington and Chelsea,71.3,73.1,79.6,80.2,73.8,67.2,NaN,92.4,91,89.6,92.1,79.4,76.6
21,E09000021,Kingston upon Thames,68.7,71,70.1,71.6,70,73.2,NaN,83.3,87.3,87.7,87,78.3,80.6
22,E09000022,Lambeth,53,61.1,62.8,65.9,57,56.5,NaN,74.2,80.1,85,86.4,68.2,67.5
23,E09000023,Lewisham,48,55.9,55.6,58,51.3,51.9,NaN,64,68.8,74.6,79,59,62.3
24,E09000024,Merton,52.4,59.8,59.1,62.6,64.2,60,NaN,77.1,85.8,84.6,85.6,70.8,70.5
25,E09000025,Newham,52.1,58.5,61.9,58.4,55.4,59.4,NaN,69.2,75.7,79.4,79.1,66,70.8
26,E09000026,Redbridge,69.3,68.5,70.6,70.2,68.1,63.4,NaN,81.2,81.8,87,86.8,77.1,75.5
27,E09000027,Richmond upon Thames,61.4,63.2,62.6,68.3,63.5,64.7,NaN,79.3,81.8,84,85.9,73.8,74
28,E09000028,Southwark,56.1,58,58.8,65.2,62.4,64.3,NaN,78.9,81.7,84.8,85.1,71.3,73.6
29,E09000029,Sutton,70.6,74.7,75.9,77,72.1,70.4,NaN,88.9,91.7,93.2,91.7,80.2,81
30,E09000030,Tower Hamlets,51.8,61.4,61.8,64.7,59.7,64.6,NaN,74.9,80.8,84.3,85.8,69.2,73.4
31,E09000031,Waltham Forest,50.9,54.3,52.6,56.7,56.7,57.4,NaN,66.6,77.2,77,78.6,66,67.9
32,E09000032,Wandsworth,58.1,61.7,58.3,61.3,59.1,58.2,NaN,79.7,84.6,85.4,83,66.8,67.9
33,E09000033,Westminster,62.5,63.1,69.9,69.6,68.1,67.5,NaN,83.9,85.9,87.5,86.8,76.8,77.5

In [ ]:
df.drop('Unnamed: 8', axis=1, inplace=True)
df

,Code,Area,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,2009/10.1,2010/11.1,2011/12.1,2012/13.1,2013/14.1,2014/15.1
1,E09000001,City of London,.,.,.,.,.,.,.,.,.,.,.,.
2,E09000002,Barking and Dagenham,51.6,57.2,58.6,60.2,58.2,54,76.5,81.2,83.3,82.5,65.5,66.4
3,E09000003,Barnet,67.3,68.8,69.2,71.5,67.5,70.1,83.2,87,85.6,87,75.4,78.1
4,E09000004,Bexley,59.8,63.3,64.9,66,60.3,55,81.1,87.3,89.4,88.6,69.4,70.8
5,E09000005,Brent,60.1,62.1,58.7,62.9,60,60,75.4,79.9,77.7,81.1,69.3,70.6
6,E09000006,Bromley,65.1,67.2,68.9,73.9,65.6,68,85.2,88.1,93.2,92.9,74.5,74.8
7,E09000007,Camden,53.1,60.2,59,60.4,60.5,56.4,68.7,73.7,77.3,77.5,68.2,67.8
8,E09000008,Croydon,54.4,61,62.2,64.4,56.8,59.6,82.9,87.4,88,85.3,68.1,69.6
9,E09000009,Ealing,58.7,57.3,57.7,60.9,59.8,62.1,76.9,76.2,78.8,80,67.9,69.7
10,E09000010,Enfield,55.3,59.5,55.5,63.2,59.7,54.5,74.1,81.2,81.1,81,68.5,65.2
11,E09000011,Greenwich,50.1,54.5,63.1,65.4,59.6,57.7,72,75.6,88.6,89.6,70.5,69.3
12,E09000012,Hackney,55.3,57,60.2,61.2,58.8,60.4,71.1,74.9,79.2,79.6,71.1,69.7
13,E09000013,Hammersmith and Fulham,68.2,71.3,65.6,66.5,65.6,62.6,89.1,91.5,83.8,83.5,73.6,73.6
14,E09000014,Haringey,48,57.3,58.6,63.5,59.1,54.6,73,77.6,78.8,83.5,69.8,65.5
15,E09000015,Harrow,60.7,64.6,63.6,65.4,62.3,60.5,78.1,80.3,83.8,82.2,71.3,73.2
16,E09000016,Havering,62.3,63.9,61.5,63.7,60.2,57.7,77.4,79.6,81.4,79.1,68.6,66.4
17,E09000017,Hillingdon,55.8,59.5,61,61.6,58.6,57.5,80.7,84.9,86.6,87.2,68.3,68
18,E09000018,Hounslow,58.7,62.5,61.8,66.7,66.1,65.2,82.4,86.8,88.1,86.8,74.4,75.5
19,E09000019,Islington,50,49.4,53.6,63.5,59.9,57.9,72,75.1,78.8,82.9,69.5,69.1
20,E09000020,Kensington and Chelsea,71.3,73.1,79.6,80.2,73.8,67.2,92.4,91,89.6,92.1,79.4,76.6
21,E09000021,Kingston upon Thames,68.7,71,70.1,71.6,70,73.2,83.3,87.3,87.7,87,78.3,80.6
22,E09000022,Lambeth,53,61.1,62.8,65.9,57,56.5,74.2,80.1,85,86.4,68.2,67.5
23,E09000023,Lewisham,48,55.9,55.6,58,51.3,51.9,64,68.8,74.6,79,59,62.3
24,E09000024,Merton,52.4,59.8,59.1,62.6,64.2,60,77.1,85.8,84.6,85.6,70.8,70.5
25,E09000025,Newham,52.1,58.5,61.9,58.4,55.4,59.4,69.2,75.7,79.4,79.1,66,70.8
26,E09000026,Redbridge,69.3,68.5,70.6,70.2,68.1,63.4,81.2,81.8,87,86.8,77.1,75.5
27,E09000027,Richmond upon Thames,61.4,63.2,62.6,68.3,63.5,64.7,79.3,81.8,84,85.9,73.8,74
28,E09000028,Southwark,56.1,58,58.8,65.2,62.4,64.3,78.9,81.7,84.8,85.1,71.3,73.6
29,E09000029,Sutton,70.6,74.7,75.9,77,72.1,70.4,88.9,91.7,93.2,91.7,80.2,81
30,E09000030,Tower Hamlets,51.8,61.4,61.8,64.7,59.7,64.6,74.9,80.8,84.3,85.8,69.2,73.4
31,E09000031,Waltham Forest,50.9,54.3,52.6,56.7,56.7,57.4,66.6,77.2,77,78.6,66,67.9
32,E09000032,Wandsworth,58.1,61.7,58.3,61.3,59.1,58.2,79.7,84.6,85.4,83,66.8,67.9
33,E09000033,Westminster,62.5,63.1,69.9,69.6,68.1,67.5,83.9,85.9,87.5,86.8,76.8,77.5

In [ ]:
df.drop(index=df.index[0], inplace=True)
df

,Code,Area,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,2009/10.1,2010/11.1,2011/12.1,2012/13.1,2013/14.1,2014/15.1
2,E09000002,Barking and Dagenham,51.6,57.2,58.6,60.2,58.2,54,76.5,81.2,83.3,82.5,65.5,66.4
3,E09000003,Barnet,67.3,68.8,69.2,71.5,67.5,70.1,83.2,87,85.6,87,75.4,78.1
4,E09000004,Bexley,59.8,63.3,64.9,66,60.3,55,81.1,87.3,89.4,88.6,69.4,70.8
5,E09000005,Brent,60.1,62.1,58.7,62.9,60,60,75.4,79.9,77.7,81.1,69.3,70.6
6,E09000006,Bromley,65.1,67.2,68.9,73.9,65.6,68,85.2,88.1,93.2,92.9,74.5,74.8
7,E09000007,Camden,53.1,60.2,59,60.4,60.5,56.4,68.7,73.7,77.3,77.5,68.2,67.8
8,E09000008,Croydon,54.4,61,62.2,64.4,56.8,59.6,82.9,87.4,88,85.3,68.1,69.6
9,E09000009,Ealing,58.7,57.3,57.7,60.9,59.8,62.1,76.9,76.2,78.8,80,67.9,69.7
10,E09000010,Enfield,55.3,59.5,55.5,63.2,59.7,54.5,74.1,81.2,81.1,81,68.5,65.2
11,E09000011,Greenwich,50.1,54.5,63.1,65.4,59.6,57.7,72,75.6,88.6,89.6,70.5,69.3
12,E09000012,Hackney,55.3,57,60.2,61.2,58.8,60.4,71.1,74.9,79.2,79.6,71.1,69.7
13,E09000013,Hammersmith and Fulham,68.2,71.3,65.6,66.5,65.6,62.6,89.1,91.5,83.8,83.5,73.6,73.6
14,E09000014,Haringey,48,57.3,58.6,63.5,59.1,54.6,73,77.6,78.8,83.5,69.8,65.5
15,E09000015,Harrow,60.7,64.6,63.6,65.4,62.3,60.5,78.1,80.3,83.8,82.2,71.3,73.2
16,E09000016,Havering,62.3,63.9,61.5,63.7,60.2,57.7,77.4,79.6,81.4,79.1,68.6,66.4
17,E09000017,Hillingdon,55.8,59.5,61,61.6,58.6,57.5,80.7,84.9,86.6,87.2,68.3,68
18,E09000018,Hounslow,58.7,62.5,61.8,66.7,66.1,65.2,82.4,86.8,88.1,86.8,74.4,75.5
19,E09000019,Islington,50,49.4,53.6,63.5,59.9,57.9,72,75.1,78.8,82.9,69.5,69.1
20,E09000020,Kensington and Chelsea,71.3,73.1,79.6,80.2,73.8,67.2,92.4,91,89.6,92.1,79.4,76.6
21,E09000021,Kingston upon Thames,68.7,71,70.1,71.6,70,73.2,83.3,87.3,87.7,87,78.3,80.6
22,E09000022,Lambeth,53,61.1,62.8,65.9,57,56.5,74.2,80.1,85,86.4,68.2,67.5
23,E09000023,Lewisham,48,55.9,55.6,58,51.3,51.9,64,68.8,74.6,79,59,62.3
24,E09000024,Merton,52.4,59.8,59.1,62.6,64.2,60,77.1,85.8,84.6,85.6,70.8,70.5
25,E09000025,Newham,52.1,58.5,61.9,58.4,55.4,59.4,69.2,75.7,79.4,79.1,66,70.8
26,E09000026,Redbridge,69.3,68.5,70.6,70.2,68.1,63.4,81.2,81.8,87,86.8,77.1,75.5
27,E09000027,Richmond upon Thames,61.4,63.2,62.6,68.3,63.5,64.7,79.3,81.8,84,85.9,73.8,74
28,E09000028,Southwark,56.1,58,58.8,65.2,62.4,64.3,78.9,81.7,84.8,85.1,71.3,73.6
29,E09000029,Sutton,70.6,74.7,75.9,77,72.1,70.4,88.9,91.7,93.2,91.7,80.2,81
30,E09000030,Tower Hamlets,51.8,61.4,61.8,64.7,59.7,64.6,74.9,80.8,84.3,85.8,69.2,73.4
31,E09000031,Waltham Forest,50.9,54.3,52.6,56.7,56.7,57.4,66.6,77.2,77,78.6,66,67.9
32,E09000032,Wandsworth,58.1,61.7,58.3,61.3,59.1,58.2,79.7,84.6,85.4,83,66.8,67.9
33,E09000033,Westminster,62.5,63.1,69.9,69.6,68.1,67.5,83.9,85.9,87.5,86.8,76.8,77.5

In [ ]:
df.rename(columns={'Unnamed: 1': 'Area',
                   'Unnamed: 3':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs',
                   'Unnamed: 4':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs',
                   'Unnamed: 5':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs',
                   'Unnamed: 6':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs',
                   'Unnamed: 7':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs',
                   'Unnamed: 10':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades	',
                   'Unnamed: 11':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades	',
                   'Unnamed: 12':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades	',
                   'Unnamed: 13':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades	',
                   'Unnamed: 14':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades	',
                   }, inplace=True)

df

,Code,Area,2009/10,2010/11,2011/12,2012/13,2013/14,2014/15,2009/10.1,2010/11.1,2011/12.1,2012/13.1,2013/14.1,2014/15.1
2,E09000002,Barking and Dagenham,51.6,57.2,58.6,60.2,58.2,54,76.5,81.2,83.3,82.5,65.5,66.4
3,E09000003,Barnet,67.3,68.8,69.2,71.5,67.5,70.1,83.2,87,85.6,87,75.4,78.1
4,E09000004,Bexley,59.8,63.3,64.9,66,60.3,55,81.1,87.3,89.4,88.6,69.4,70.8
5,E09000005,Brent,60.1,62.1,58.7,62.9,60,60,75.4,79.9,77.7,81.1,69.3,70.6
6,E09000006,Bromley,65.1,67.2,68.9,73.9,65.6,68,85.2,88.1,93.2,92.9,74.5,74.8
7,E09000007,Camden,53.1,60.2,59,60.4,60.5,56.4,68.7,73.7,77.3,77.5,68.2,67.8
8,E09000008,Croydon,54.4,61,62.2,64.4,56.8,59.6,82.9,87.4,88,85.3,68.1,69.6
9,E09000009,Ealing,58.7,57.3,57.7,60.9,59.8,62.1,76.9,76.2,78.8,80,67.9,69.7
10,E09000010,Enfield,55.3,59.5,55.5,63.2,59.7,54.5,74.1,81.2,81.1,81,68.5,65.2
11,E09000011,Greenwich,50.1,54.5,63.1,65.4,59.6,57.7,72,75.6,88.6,89.6,70.5,69.3
12,E09000012,Hackney,55.3,57,60.2,61.2,58.8,60.4,71.1,74.9,79.2,79.6,71.1,69.7
13,E09000013,Hammersmith and Fulham,68.2,71.3,65.6,66.5,65.6,62.6,89.1,91.5,83.8,83.5,73.6,73.6
14,E09000014,Haringey,48,57.3,58.6,63.5,59.1,54.6,73,77.6,78.8,83.5,69.8,65.5
15,E09000015,Harrow,60.7,64.6,63.6,65.4,62.3,60.5,78.1,80.3,83.8,82.2,71.3,73.2
16,E09000016,Havering,62.3,63.9,61.5,63.7,60.2,57.7,77.4,79.6,81.4,79.1,68.6,66.4
17,E09000017,Hillingdon,55.8,59.5,61,61.6,58.6,57.5,80.7,84.9,86.6,87.2,68.3,68
18,E09000018,Hounslow,58.7,62.5,61.8,66.7,66.1,65.2,82.4,86.8,88.1,86.8,74.4,75.5
19,E09000019,Islington,50,49.4,53.6,63.5,59.9,57.9,72,75.1,78.8,82.9,69.5,69.1
20,E09000020,Kensington and Chelsea,71.3,73.1,79.6,80.2,73.8,67.2,92.4,91,89.6,92.1,79.4,76.6
21,E09000021,Kingston upon Thames,68.7,71,70.1,71.6,70,73.2,83.3,87.3,87.7,87,78.3,80.6
22,E09000022,Lambeth,53,61.1,62.8,65.9,57,56.5,74.2,80.1,85,86.4,68.2,67.5
23,E09000023,Lewisham,48,55.9,55.6,58,51.3,51.9,64,68.8,74.6,79,59,62.3
24,E09000024,Merton,52.4,59.8,59.1,62.6,64.2,60,77.1,85.8,84.6,85.6,70.8,70.5
25,E09000025,Newham,52.1,58.5,61.9,58.4,55.4,59.4,69.2,75.7,79.4,79.1,66,70.8
26,E09000026,Redbridge,69.3,68.5,70.6,70.2,68.1,63.4,81.2,81.8,87,86.8,77.1,75.5
27,E09000027,Richmond upon Thames,61.4,63.2,62.6,68.3,63.5,64.7,79.3,81.8,84,85.9,73.8,74
28,E09000028,Southwark,56.1,58,58.8,65.2,62.4,64.3,78.9,81.7,84.8,85.1,71.3,73.6
29,E09000029,Sutton,70.6,74.7,75.9,77,72.1,70.4,88.9,91.7,93.2,91.7,80.2,81
30,E09000030,Tower Hamlets,51.8,61.4,61.8,64.7,59.7,64.6,74.9,80.8,84.3,85.8,69.2,73.4
31,E09000031,Waltham Forest,50.9,54.3,52.6,56.7,56.7,57.4,66.6,77.2,77,78.6,66,67.9
32,E09000032,Wandsworth,58.1,61.7,58.3,61.3,59.1,58.2,79.7,84.6,85.4,83,66.8,67.9
33,E09000033,Westminster,62.5,63.1,69.9,69.6,68.1,67.5,83.9,85.9,87.5,86.8,76.8,77.5

In [ ]:
df.drop(['2009/10', '2010/11.1', '2011/12.1', '2012/13.1', '2013/14.1', '2014/15.1','2009/10.1'], axis=1, inplace=True)
df

         Code                    Area 2010/11 2011/12 2012/13 2013/14 2014/15
2   E09000002    Barking and Dagenham    57.2    58.6    60.2    58.2      54
3   E09000003                  Barnet    68.8    69.2    71.5    67.5    70.1
4   E09000004                  Bexley    63.3    64.9      66    60.3      55
5   E09000005                   Brent    62.1    58.7    62.9      60      60
6   E09000006                 Bromley    67.2    68.9    73.9    65.6      68
7   E09000007                  Camden    60.2      59    60.4    60.5    56.4
8   E09000008                 Croydon      61    62.2    64.4    56.8    59.6
9   E09000009                  Ealing    57.3    57.7    60.9    59.8    62.1
10  E09000010                 Enfield    59.5    55.5    63.2    59.7    54.5
11  E09000011               Greenwich    54.5    63.1    65.4    59.6    57.7
12  E09000012                 Hackney      57    60.2    61.2    58.8    60.4
13  E09000013  Hammersmith and Fulham    71.3    65.6    66.5    65.6    62.6
14  E09000014                Haringey    57.3    58.6    63.5    59.1    54.6
15  E09000015                  Harrow    64.6    63.6    65.4    62.3    60.5
16  E09000016                Havering    63.9    61.5    63.7    60.2    57.7
17  E09000017              Hillingdon    59.5      61    61.6    58.6    57.5
18  E09000018                Hounslow    62.5    61.8    66.7    66.1    65.2
19  E09000019               Islington    49.4    53.6    63.5    59.9    57.9
20  E09000020  Kensington and Chelsea    73.1    79.6    80.2    73.8    67.2
21  E09000021    Kingston upon Thames      71    70.1    71.6      70    73.2
22  E09000022                 Lambeth    61.1    62.8    65.9      57    56.5
23  E09000023                Lewisham    55.9    55.6      58    51.3    51.9
24  E09000024                  Merton    59.8    59.1    62.6    64.2      60
25  E09000025                  Newham    58.5    61.9    58.4    55.4    59.4
26  E09000026               Redbridge    68.5    70.6    70.2    68.1    63.4
27  E09000027    Richmond upon Thames    63.2    62.6    68.3    63.5    64.7
28  E09000028               Southwark      58    58.8    65.2    62.4    64.3
29  E09000029                  Sutton    74.7    75.9      77    72.1    70.4
30  E09000030           Tower Hamlets    61.4    61.8    64.7    59.7    64.6
31  E09000031          Waltham Forest    54.3    52.6    56.7    56.7    57.4
32  E09000032              Wandsworth    61.7    58.3    61.3    59.1    58.2
33  E09000033             Westminster    63.1    69.9    69.6    68.1    67.5

In [ ]:
gcse_results=df
gcse_results

         Code                    Area 2010/11 2011/12 2012/13 2013/14 2014/15
2   E09000002    Barking and Dagenham    57.2    58.6    60.2    58.2      54
3   E09000003                  Barnet    68.8    69.2    71.5    67.5    70.1
4   E09000004                  Bexley    63.3    64.9      66    60.3      55
5   E09000005                   Brent    62.1    58.7    62.9      60      60
6   E09000006                 Bromley    67.2    68.9    73.9    65.6      68
7   E09000007                  Camden    60.2      59    60.4    60.5    56.4
8   E09000008                 Croydon      61    62.2    64.4    56.8    59.6
9   E09000009                  Ealing    57.3    57.7    60.9    59.8    62.1
10  E09000010                 Enfield    59.5    55.5    63.2    59.7    54.5
11  E09000011               Greenwich    54.5    63.1    65.4    59.6    57.7
12  E09000012                 Hackney      57    60.2    61.2    58.8    60.4
13  E09000013  Hammersmith and Fulham    71.3    65.6    66.5    65.6    62.6
14  E09000014                Haringey    57.3    58.6    63.5    59.1    54.6
15  E09000015                  Harrow    64.6    63.6    65.4    62.3    60.5
16  E09000016                Havering    63.9    61.5    63.7    60.2    57.7
17  E09000017              Hillingdon    59.5      61    61.6    58.6    57.5
18  E09000018                Hounslow    62.5    61.8    66.7    66.1    65.2
19  E09000019               Islington    49.4    53.6    63.5    59.9    57.9
20  E09000020  Kensington and Chelsea    73.1    79.6    80.2    73.8    67.2
21  E09000021    Kingston upon Thames      71    70.1    71.6      70    73.2
22  E09000022                 Lambeth    61.1    62.8    65.9      57    56.5
23  E09000023                Lewisham    55.9    55.6      58    51.3    51.9
24  E09000024                  Merton    59.8    59.1    62.6    64.2      60
25  E09000025                  Newham    58.5    61.9    58.4    55.4    59.4
26  E09000026               Redbridge    68.5    70.6    70.2    68.1    63.4
27  E09000027    Richmond upon Thames    63.2    62.6    68.3    63.5    64.7
28  E09000028               Southwark      58    58.8    65.2    62.4    64.3
29  E09000029                  Sutton    74.7    75.9      77    72.1    70.4
30  E09000030           Tower Hamlets    61.4    61.8    64.7    59.7    64.6
31  E09000031          Waltham Forest    54.3    52.6    56.7    56.7    57.4
32  E09000032              Wandsworth    61.7    58.3    61.3    59.1    58.2
33  E09000033             Westminster    63.1    69.9    69.6    68.1    67.5

In [ ]:
df.drop('Unnamed: 8', axis=1, inplace=True)
df

KeyError: "['Unnamed: 8'] not found in axis"