<a href="https://colab.research.google.com/github/YJInn0121/QM2-Group-Project/blob/main/Data_cleaned_as_a_whole.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded=files.upload()
! pip install pandas
import pandas as pd
df = pd.read_excel("personal-well-being-borough.xlsx")
df.dropna(how='all', inplace=True)
df.drop(2, inplace=True)
df.drop(['Unnamed: 6','Unnamed: 7','Unnamed: 8','Unnamed: 9'], axis=1, inplace=True)
df = df.loc[:, ['Unnamed: 1','Life Satisfaction', 'Unnamed: 3', 'Unnamed: 4','Unnamed: 5']]
df.drop(df.index[35:52], inplace=True)
df.rename(columns={'Unnamed: 1': 'Area',

                   'Life Satisfaction':'Life Satisfaction 2011/2012',
                   'Unnamed: 3':'Life Satisfaction 2012/2013',
                   'Unnamed: 4':'Life Satisfaction 2013/2014',
                   'Unnamed: 5':'Life Satisfaction 2014/2015',

                   }, inplace=True)
df.drop(index=df.index[0], inplace=True)
life_satisfaction=df
life_satisfaction

Saving personal-well-being-borough.xlsx to personal-well-being-borough.xlsx
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

,Area,Life Satisifaction 2011/2012,Life Satisfaction 2012/2013,Life Satisfaction 2013/2014,Life Satisfaction 2014/2015
3,Barking and Dagenham,7.05,7.09,7.01,7.32
4,Barnet,7.43,7.28,7.4,7.54
5,Bexley,7.42,7.42,7.28,7.52
6,Brent,7.11,7.28,7.41,7.24
7,Bromley,7.5,7.6,7.53,7.71
8,Camden,7.25,7.24,7.11,7.25
9,Croydon,7.04,7.01,7.36,7.35
10,Ealing,7.22,7.22,7.24,7.6
11,Enfield,7.23,7.24,7.28,7.45
12,Greenwich,7.18,7.15,7.15,7.33
13,Hackney,7,7.07,7.05,7.43
14,Hammersmith and Fulham,7.38,7.21,7.4,7.56
15,Haringey,7.11,7.17,7.28,7.38
16,Harrow,7.31,7.37,7.51,7.49
17,Havering,7.35,7.36,7.51,7.62
18,Hillingdon,7.4,7.37,7.5,7.63
19,Hounslow,7.26,7.35,7.33,7.57
20,Islington,7.09,7.14,7.35,7.36
21,Kensington and Chelsea,7.57,7.7,7.67,7.65
22,Kingston upon Thames,7.33,7.17,7.43,7.52
23,Lambeth,7.13,7.08,7.01,7.41
24,Lewisham,7.05,7.23,7.34,7.33
25,Merton,7.14,7.18,7.43,7.64
26,Newham,7.12,7.23,7.24,7.54
27,Redbridge,7.33,7.3,7.47,7.55
28,Richmond upon Thames,7.52,7.4,7.6,7.54
29,Southwark,7.36,7.21,7.58,7.43
30,Sutton,7.39,7.28,7.49,7.6
31,Tower Hamlets,7.02,7.32,7.5,7.54
32,Waltham Forest,7.18,7.24,7.34,7.64
33,Wandsworth,7.46,7.26,7.43,7.47
34,Westminster,7.33,7,7.53,7.45
36,North East,7.44,7.39,7.47,7.57
37,North West,7.37,7.41,7.42,7.56

In [ ]:
from google.colab import files
uploaded=files.upload()
! pip install pandas
import pandas as pd
df = pd.read_excel("personal-well-being-borough.xlsx")
df.dropna(how='all', inplace=True)
df.drop(2, inplace=True)
df = df.loc[:, ['Unnamed: 1','Anxiety', 'Unnamed: 30', 'Unnamed: 31','Unnamed: 32']]
df.rename(columns={'Unnamed: 1': 'Area',

                   'Anxiety':'Anxiety 2011/2012',
                   'Unnamed: 30':'Anxiety 2012/2013',
                   'Unnamed: 31':'Anxiety 2013/2014',
                   'Unnamed: 32':'Anxiety 2014/2015',

                   }, inplace=True)
df.drop(df.index[33:52], inplace=True)
df.drop(index=df.index[0], inplace=True)
life_anxiety=df
life_anxiety

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

,Area,Anxiety 2011/2012,Anxiety 2012/2013,Anxiety 2013/2014,Anxiety 2014/2015
3,Barking and Dagenham,3.23,3.27,3.39,3.15
4,Barnet,3.41,2.74,2.6,2.37
5,Bexley,3.07,3.24,3.46,3.16
6,Brent,2.77,3.29,3.07,2.5
7,Bromley,3.3,3.22,3.15,2.76
8,Camden,3.81,3.24,3.41,3.21
9,Croydon,3.47,3.04,3.32,2.89
10,Ealing,3.86,3.58,3.38,3.36
11,Enfield,3.15,2.54,2.57,2.19
12,Greenwich,3.38,3.62,3.27,3.52
13,Hackney,3.88,3.66,3.79,3.32
14,Hammersmith and Fulham,2.87,3.09,3.4,3.14
15,Haringey,3.3,3.06,3.24,3
16,Harrow,2.65,3.14,2.6,2.57
17,Havering,3.4,3.17,3.12,3.02
18,Hillingdon,3.44,3.37,3.06,3.03
19,Hounslow,3.54,3.39,3.17,3.25
20,Islington,3.66,3.68,3.45,3.27
21,Kensington and Chelsea,3.2,3,3.14,3.21
22,Kingston upon Thames,3.5,3.34,3.07,3.2
23,Lambeth,3.43,3.66,3.42,3.12
24,Lewisham,3.56,3.36,3.4,3.23
25,Merton,3.78,3.59,3.38,3.31
26,Newham,3.89,3.33,2.85,2.72
27,Redbridge,3.3,3.11,3.16,3.02
28,Richmond upon Thames,3.32,3.49,3.01,3.34
29,Southwark,3.54,3.37,3.49,3.29
30,Sutton,3.22,3.34,3.28,3.04
31,Tower Hamlets,3.53,2.95,3.05,3.14
32,Waltham Forest,3.45,2.96,3.03,2.79
33,Wandsworth,3.63,3.54,3.34,3.07
34,Westminster,3.52,3.66,3.13,3.38

In [ ]:
from google.colab import files
uploaded=files.upload()
! pip install pandas
import pandas as pd
df = pd.read_excel("gcse-results-old.xls")
df.dropna(how='all', inplace=True)
df.drop(2, inplace=True)
df.drop(df.index[33:50], inplace=True)
df.drop('Unnamed: 8', axis=1, inplace=True)
df.drop('Unnamed: 0', axis=1, inplace=True)
df.drop('Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs', axis=1, inplace=True)
df.drop('Unnamed: 3', axis=1, inplace=True)
df.drop('Unnamed: 10', axis=1, inplace=True)











df.drop('Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades', axis=1, inplace=True)
df.rename(columns={'Unnamed: 1': 'Area',
                   'Unnamed: 4':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs 2011/12',
                   'Unnamed: 5':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs 2012/13',
                   'Unnamed: 6':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs 2013/2014',
                   'Unnamed: 7':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs 2014/2015',
                   'Unnamed: 11':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades 2011/2012	',
                   'Unnamed: 12':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades 2012/2013',
                   'Unnamed: 13':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades	2013/2014',
                   'Unnamed: 14':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades 2014/2015',





                   }, inplace=True)
df.drop(index=df.index[0], inplace=True)
gcse_df=df
gcse_df

Saving gcse-results-old.xls to gcse-results-old.xls
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

,Area,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs 2011/12,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs 2012/13,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs 2013/2014,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs 2014/2015,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades 2011/2012\t,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades 2012/2013,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades\t2013/2014,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades 2014/2015
3,Barking and Dagenham,58.6,60.2,58.2,54,83.3,82.5,65.5,66.4
4,Barnet,69.2,71.5,67.5,70.1,85.6,87,75.4,78.1
5,Bexley,64.9,66,60.3,55,89.4,88.6,69.4,70.8
6,Brent,58.7,62.9,60,60,77.7,81.1,69.3,70.6
7,Bromley,68.9,73.9,65.6,68,93.2,92.9,74.5,74.8
8,Camden,59,60.4,60.5,56.4,77.3,77.5,68.2,67.8
9,Croydon,62.2,64.4,56.8,59.6,88,85.3,68.1,69.6
10,Ealing,57.7,60.9,59.8,62.1,78.8,80,67.9,69.7
11,Enfield,55.5,63.2,59.7,54.5,81.1,81,68.5,65.2
12,Greenwich,63.1,65.4,59.6,57.7,88.6,89.6,70.5,69.3
13,Hackney,60.2,61.2,58.8,60.4,79.2,79.6,71.1,69.7
14,Hammersmith and Fulham,65.6,66.5,65.6,62.6,83.8,83.5,73.6,73.6
15,Haringey,58.6,63.5,59.1,54.6,78.8,83.5,69.8,65.5
16,Harrow,63.6,65.4,62.3,60.5,83.8,82.2,71.3,73.2
17,Havering,61.5,63.7,60.2,57.7,81.4,79.1,68.6,66.4
18,Hillingdon,61,61.6,58.6,57.5,86.6,87.2,68.3,68
19,Hounslow,61.8,66.7,66.1,65.2,88.1,86.8,74.4,75.5
20,Islington,53.6,63.5,59.9,57.9,78.8,82.9,69.5,69.1
21,Kensington and Chelsea,79.6,80.2,73.8,67.2,89.6,92.1,79.4,76.6
22,Kingston upon Thames,70.1,71.6,70,73.2,87.7,87,78.3,80.6
23,Lambeth,62.8,65.9,57,56.5,85,86.4,68.2,67.5
24,Lewisham,55.6,58,51.3,51.9,74.6,79,59,62.3
25,Merton,59.1,62.6,64.2,60,84.6,85.6,70.8,70.5
26,Newham,61.9,58.4,55.4,59.4,79.4,79.1,66,70.8
27,Redbridge,70.6,70.2,68.1,63.4,87,86.8,77.1,75.5
28,Richmond upon Thames,62.6,68.3,63.5,64.7,84,85.9,73.8,74
29,Southwark,58.8,65.2,62.4,64.3,84.8,85.1,71.3,73.6
30,Sutton,75.9,77,72.1,70.4,93.2,91.7,80.2,81
31,Tower Hamlets,61.8,64.7,59.7,64.6,84.3,85.8,69.2,73.4
32,Waltham Forest,52.6,56.7,56.7,57.4,77,78.6,66,67.9
33,Wandsworth,58.3,61.3,59.1,58.2,85.4,83,66.8,67.9
34,Westminster,69.9,69.6,68.1,67.5,87.5,86.8,76.8,77.5

In [ ]:
#gcse results
from google.colab import files
uploaded=files.upload()
! pip install pandas
import pandas as pd
df = pd.read_excel("gcse-results-old.xls",header=1)
df.dropna(how='all', inplace=True)
df.drop(df.index[33:50], inplace=True)
df.drop('Unnamed: 8', axis=1, inplace=True)
df.drop(index=df.index[0], inplace=True)
df.rename(columns={'Unnamed: 1': 'Area',
                   'Unnamed: 3':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs',
                   'Unnamed: 4':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs',
                   'Unnamed: 5':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs',
                   'Unnamed: 6':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs',
                   'Unnamed: 7':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs',
                   'Unnamed: 10':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades	',
                   'Unnamed: 11':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades	',
                   'Unnamed: 12':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades	',
                   'Unnamed: 13':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades	',
                   'Unnamed: 14':'Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades	',
                   }, inplace=True)
df.drop(['2009/10', '2010/11.1', '2011/12.1', '2012/13.1', '2013/14.1', '2014/15.1','2009/10.1'], axis=1, inplace=True)
gcse_results=df
gcse_results

Saving gcse-results-old.xls to gcse-results-old (1).xls
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

         Code                    Area 2010/11 2011/12 2012/13 2013/14 2014/15
2   E09000002    Barking and Dagenham    57.2    58.6    60.2    58.2      54
3   E09000003                  Barnet    68.8    69.2    71.5    67.5    70.1
4   E09000004                  Bexley    63.3    64.9      66    60.3      55
5   E09000005                   Brent    62.1    58.7    62.9      60      60
6   E09000006                 Bromley    67.2    68.9    73.9    65.6      68
7   E09000007                  Camden    60.2      59    60.4    60.5    56.4
8   E09000008                 Croydon      61    62.2    64.4    56.8    59.6
9   E09000009                  Ealing    57.3    57.7    60.9    59.8    62.1
10  E09000010                 Enfield    59.5    55.5    63.2    59.7    54.5
11  E09000011               Greenwich    54.5    63.1    65.4    59.6    57.7
12  E09000012                 Hackney      57    60.2    61.2    58.8    60.4
13  E09000013  Hammersmith and Fulham    71.3    65.6    66.5    65.6    62.6
14  E09000014                Haringey    57.3    58.6    63.5    59.1    54.6
15  E09000015                  Harrow    64.6    63.6    65.4    62.3    60.5
16  E09000016                Havering    63.9    61.5    63.7    60.2    57.7
17  E09000017              Hillingdon    59.5      61    61.6    58.6    57.5
18  E09000018                Hounslow    62.5    61.8    66.7    66.1    65.2
19  E09000019               Islington    49.4    53.6    63.5    59.9    57.9
20  E09000020  Kensington and Chelsea    73.1    79.6    80.2    73.8    67.2
21  E09000021    Kingston upon Thames      71    70.1    71.6      70    73.2
22  E09000022                 Lambeth    61.1    62.8    65.9      57    56.5
23  E09000023                Lewisham    55.9    55.6      58    51.3    51.9
24  E09000024                  Merton    59.8    59.1    62.6    64.2      60
25  E09000025                  Newham    58.5    61.9    58.4    55.4    59.4
26  E09000026               Redbridge    68.5    70.6    70.2    68.1    63.4
27  E09000027    Richmond upon Thames    63.2    62.6    68.3    63.5    64.7
28  E09000028               Southwark      58    58.8    65.2    62.4    64.3
29  E09000029                  Sutton    74.7    75.9      77    72.1    70.4
30  E09000030           Tower Hamlets    61.4    61.8    64.7    59.7    64.6
31  E09000031          Waltham Forest    54.3    52.6    56.7    56.7    57.4
32  E09000032              Wandsworth    61.7    58.3    61.3    59.1    58.2
33  E09000033             Westminster    63.1    69.9    69.6    68.1    67.5

In [ ]:
from google.colab import files
uploaded=files.upload()
! pip install pandas
import pandas as pd
df = pd.read_excel("sports-participation-borough-region.xls")
df = df.drop(df.index[1:13])
df = df.drop([
              'Unnamed: 1',
              'APS1 2005/06',
              'Unnamed: 4',
              'APS2 2007/08',
              'Unnamed: 6',
              'APS3 2008/09',
              'Unnamed: 8',
              'APS4 2009/10',
              'Unnamed: 10',
              'APS5 2010/11',
              'Unnamed: 12',
              'APS10 (2015/2016',
              'Unnamed: 22'
              ], axis=1)
df.rename(columns={'Unnamed: 2':'Area',

                   'APS6 2011/12':'2011/2012',
                   'APS7 2012/13':'2012/2013',
                   'APS8 2013/14':'2013/2014',
                   'APS9 2014/15':'2014/2015',

                   }, inplace=True)
df.drop(index=df.index[0], inplace=True)
sports_particpation=df
sports_particpation

Saving sports-participation-borough-region.xls to sports-participation-borough-region.xls
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

,Age 16+ Sports participation - At least three times a week\n,Area,2011/2012,Unnamed: 14,2012/2013,Unnamed: 16,2013/2014,Unnamed: 18,2014/2015,Unnamed: 20
13,E09000002,Barking and Dagenham,0.131,18100,0.135,18900,0.119,16800,0.141,20400
14,E09000003,Barnet,0.175,49700,0.184,52900,0.162,47000,0.181,53400
15,E09000004,Bexley,0.14,26000,0.184,34300,0.174,32500,0.147,28000
16,E09000005,Brent,0.184,45900,0.145,36300,0.191,48100,0.124,31500
17,E09000006,Bromley,0.166,41600,0.187,47200,0.151,38400,0.213,54700
18,E09000007,Camden,0.183,33800,0.233,43800,0.224,42600,0.228,44300
19,E09000008,Croydon,0.196,56000,0.174,50100,0.124,36000,0.176,51600
20,E09000009,Ealing,0.165,44600,0.208,56300,0.202,54500,0.154,41400
21,E09000010,Enfield,0.152,37100,0.146,35800,0.156,38500,0.161,40300
22,E09000011,Greenwich,0.154,30800,0.151,30800,0.159,32600,0.154,32200
23,E09000012,Hackney,0.207,40700,0.179,35700,0.194,39400,0.179,37300
24,E09000013,Hammersmith and Fulham,0.197,30100,0.273,40900,0.254,37500,0.24,35300
25,E09000014,Haringey,0.176,35900,0.18,37000,0.195,40900,0.228,48700
26,E09000015,Harrow,0.158,30400,0.144,27900,0.147,28500,0.171,33500
27,E09000016,Havering,0.168,32500,0.175,34100,0.158,30900,0.167,33200
28,E09000017,Hillingdon,0.157,34400,0.213,47300,0.171,38500,0.134,30800
29,E09000018,Hounslow,0.204,41600,0.164,33600,0.203,42000,0.202,42300
30,E09000019,Islington,0.207,36000,0.235,41700,0.196,35400,0.221,40900
31,E09000020,Kensington and Chelsea,0.285,38200,0.252,33100,0.2,26000,0.251,32800
32,E09000021,Kingston upon Thames,0.206,26800,0.195,25800,0.21,28200,0.181,24700
33,E09000022,Lambeth,0.203,50800,0.231,58700,0.248,63800,0.216,56500
34,E09000023,Lewisham,0.182,40000,0.144,32000,0.131,29500,0.159,36600
35,E09000024,Merton,0.161,26000,0.226,36600,0.186,30200,0.241,39000
36,E09000025,Newham,0.149,35800,0.169,41000,0.152,37100,0.14,34900
37,E09000026,Redbridge,0.175,38300,0.168,36900,0.198,44000,0.181,40900
38,E09000027,Richmond upon Thames,0.244,36700,0.266,40100,0.225,34100,0.25,38300
39,E09000028,Southwark,0.193,45500,0.191,45600,0.166,40300,0.156,38300
40,E09000029,Sutton,0.154,23600,0.191,29600,0.148,23000,0.181,28500
41,E09000030,Tower Hamlets,0.167,34400,0.185,38800,0.2,43400,0.174,39400
42,E09000031,Waltham Forest,0.176,36100,0.171,35200,0.155,32100,0.145,30400
43,E09000032,Wandsworth,0.239,61300,0.233,59600,0.213,54400,0.282,72400
44,E09000033,Westminster,0.237,44300,0.234,44300,0.218,41400,0.224,43900

In [ ]:
from google.colab import files
uploaded=files.upload()
! pip install pandas
import pandas as pd
df = pd.read_csv("MPS Borough Level Crime.csv")
df = df.drop([
              '201004', '201005','201006','201007','201008','201009','201010','201011',
              '201101','201102','201103','201104','201105','201106','201107',
              '201012','201509','201510','201511','201512','201601','201602','201602', '201603', '201604', '201605', '201606',
              '201607', '201608', '201609', '201610', '201611', '201612', '201701', '201702',
              '201703', '201704', '201705', '201706', '201707', '201708', '201709', '201710',
              '201711', '201712', '201801', '201802', '201803', '201804', '201805', '201806', '201807',
              '201808', '201809', '201810', '201811', '201812', '201901', '201902', '201903', '201904',
              '201905', '201906', '201907', '201908', '201909', '201910', '201911', '201912', '202001',
              '202002', '202003', '202004', '202005', '202006', '202007', '202008', '202009', '202010',
              '202011', '202012', '202101', '202102', '202103', '202104', '202105', '202106', '202107'


              ], axis=1)
df.rename(columns={'LookUp_BoroughName': 'Area'}, inplace=True)
crime=df
crime

Saving MPS Borough Level Crime.csv to MPS Borough Level Crime.csv
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

,MajorText,MinorText,Area,201108,201109,201110,201111,201112,201201,201202,...,201411,201412,201501,201502,201503,201504,201505,201506,201507,201508
0,Arson and Criminal Damage,Arson,Barking and Dagenham,17,6,15,13,5,10,4,...,10,5,3,3,10,5,8,5,11,9
1,Arson and Criminal Damage,Criminal Damage,Barking and Dagenham,193,149,137,150,161,136,113,...,117,113,117,113,143,132,170,130,162,130
2,Burglary,Burglary Business and Community,Barking and Dagenham,99,66,65,64,53,46,43,...,42,33,21,28,40,42,41,26,42,56
3,Burglary,Domestic Burglary,Barking and Dagenham,97,98,136,167,181,184,149,...,180,133,161,110,129,65,61,68,89,89
4,Drug Offences,Drug Trafficking,Barking and Dagenham,10,5,2,13,3,6,6,...,8,2,2,5,5,3,5,8,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1720,Vehicle Offences,Theft from a Motor Vehicle,Westminster,156,213,198,234,182,176,129,...,185,201,177,152,170,137,152,159,193,158
1721,Vehicle Offences,Theft or Taking of a Motor Vehicle,Westminster,38,41,38,35,33,52,19,...,68,50,72,58,71,72,91,88,64,68
1722,Violence Against the Person,Homicide,Westminster,0,0,0,0,1,0,0,...,0,2,1,2,0,0,0,0,0,0
1723,Violence Against the Person,Violence with Injury,Westminster,244,293,328,315,306,271,211,...,259,295,255,247,281,265,291,280,275,292
1724,Violence Against the Person,Violence without Injury,Westminster,236,248,305,310,300,271,287,...,360,325,314,379,364,314,393,401,396,416

In [ ]:
crime_data = crime.groupby('Area').sum()
crime_data

<ipython-input-13-9bf9b8c77b06>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  crime_data = crime.groupby('Area').sum()

,201108,201109,201110,201111,201112,201201,201202,201203,201204,201205,...,201411,201412,201501,201502,201503,201504,201505,201506,201507,201508
Area,,,,,,,,,,,,,,,,,,,,,
Barking and Dagenham,1676,1411,1415,1504,1438,1529,1396,1672,1359,1495,...,1476,1284,1308,1219,1543,1342,1495,1440,1584,1409
Barnet,2076,1965,2163,2274,2026,1987,2033,2392,2092,2132,...,1989,1947,1990,1844,1969,1922,1960,2105,2192,2011
Bexley,1042,936,911,1037,857,971,925,1147,981,1160,...,1039,1042,1076,875,1066,917,1088,1052,1029,873
Brent,2388,2343,2795,2700,2438,2632,2352,2613,2216,2389,...,2097,1941,1989,1871,2152,2014,2189,2141,2052,1998
Bromley,1865,1748,1800,1828,1875,1827,1674,1815,1515,1724,...,1750,1751,1713,1629,1791,1724,1777,1825,1809,1744
Camden,2745,2840,3080,3150,2754,2720,2505,3065,2740,3151,...,2530,2494,2425,2309,2601,2514,2799,2659,2576,2306
Croydon,2999,2528,2714,2703,2302,3151,2360,2823,2560,2810,...,2525,2549,2471,2172,2622,2394,2609,2670,2473,2320
Ealing,2885,2323,2651,2626,2371,2698,2323,2775,2381,2698,...,2180,2182,2085,1961,2203,2105,2425,2435,2380,2167
Enfield,1984,1728,1901,1936,1625,1628,1773,2082,1800,2018,...,1877,1832,1866,1713,1940,1764,1909,1851,2046,1894
Greenwich,1948,1672,1705,1859,1872,1806,1606,1835,1664,1925,...,1729,1634,1813,1585,1817,1737,1847,1788,1888,1789
Hackney,2262,2272,2269,2362,1880,2315,2066,2677,2344,2481,...,2269,2050,2117,2112,2340,2211,2430,2492,2461,2234
Hammersmith and Fulham,1930,1837,1883,1967,1899,1787,1757,1938,1873,2022,...,1871,1712,1676,1499,1756,1706,1778,1658,1729,1601
Haringey,2216,1966,2116,2262,2144,2137,1947,2385,1992,2295,...,2044,1884,1927,1876,2149,2063,2009,2075,2320,2153
Harrow,1152,1037,1151,1176,1173,1219,1110,1317,1053,1174,...,1089,970,1015,1035,1058,983,1142,1044,961,1041
Havering,1462,1342,1395,1393,1327,1361,1426,1597,1332,1437,...,1268,1331,1274,1193,1332,1200,1276,1426,1471,1332
Hillingdon,1888,2053,2145,1921,2013,2014,1715,2027,1815,1842,...,2000,1752,1788,1751,1837,1730,1832,1921,1787,1709
Hounslow,1874,1996,2045,2169,1772,2216,1852,2186,1971,2017,...,1769,1771,1735,1690,1759,1626,1823,1851,1979,1752
Islington,2058,2056,2324,2509,1969,2085,1941,2473,2345,2516,...,2307,2248,2192,2174,2470,2381,2492,2396,2397,2215
Kensington and Chelsea,1967,1521,1547,1824,1742,1744,1530,1882,1719,1796,...,1551,1617,1561,1410,1615,1470,1636,1632,1647,1744
Kingston upon Thames,857,896,1033,983,963,940,862,961,835,861,...,921,866,792,796,822,777,845,891,862,814
Lambeth,3080,3038,3107,3142,2812,3361,2445,3235,2906,2905,...,2799,2652,2502,2507,2848,2769,3009,2837,3081,3063
Lewisham,2423,2166,2327,2254,2046,2162,1908,2380,1946,2170,...,1797,1845,1804,1822,1985,1971,2111,2105,2122,2037
London Heathrow and London City Airports,295,256,232,254,246,214,227,208,206,208,...,242,252,231,196,244,223,267,272,303,278
Merton,1123,1028,1268,1224,1085,1073,1131,1235,1085,1219,...,1137,1072,1057,940,996,970,1127,1054,1153,1063
Newham,2665,2550,2699,2556,2261,2478,2410,3094,2578,2770,...,2485,2424,2551,2329,2650,2235,2420,2590,2710,2447
Redbridge,1982,1865,2194,2116,1780,1985,1768,2075,1741,1943,...,1769,1748,1628,1513,1699,1504,1515,1744,1656,1478
Richmond upon Thames,1004,982,1013,960,932,907,855,1064,978,1205,...,965,857,871,759,938,893,996,892,889,907
Southwark,2899,2715,3107,2896,2791,2663,2595,2904,2408,2922,...,2683,2385,2536,2314,2506,2469,2862,2689,2672,2618
Sutton,976,888,931,916,896,877,905,1043,930,994,...,1037,977,853,930,982,930,867,1022,838,871
Tower Hamlets,2613,2264,2331,2406,2120,2296,2237,2455,2221,2398,...,2404,2237,2245,2131,2358,2135,2481,2358,2719,2411
Waltham Forest,2180,1816,2043,2074,1867,1778,1775,2160,2060,2194,...,1752,1618,1713,1569,1854,1732,1681,1934,1958,1804
Wandsworth,1924,1868,2040,1989,1956,1979,2022,2507,2087,2234,...,1988,1848,1832,1757,2022,1886,2056,1978,1973,1833
Westminster,4977,4882,5643,5591,5601,5386,4716,5824,4922,5432,...,4100,4469,4174,3500,4084,3879,4165,3926,4067,4094

In [ ]:
crime_data['2011/2012'] = crime_data.loc[:, '201108':'201207'].sum(axis=1)
crime_data['2012/2013'] = crime_data.loc[:, '201208':'201307'].sum(axis=1)
crime_data['2013/2014'] = crime_data.loc[:, '201308':'201407'].sum(axis=1)
crime_data['2014/2015'] = crime_data.loc[:, '201408':'201507'].sum(axis=1)
print(crime_data)

                                          201108  201109  201110  201111  \
Area
Barking and Dagenham                        1676    1411    1415    1504
Barnet                                      2076    1965    2163    2274
Bexley                                      1042     936     911    1037
Brent                                       2388    2343    2795    2700
Bromley                                     1865    1748    1800    1828
Camden                                      2745    2840    3080    3150
Croydon                                     2999    2528    2714    2703
Ealing                                      2885    2323    2651    2626
Enfield                                     1984    1728    1901    1936
Greenwich                                   1948    1672    1705    1859
Hackney                                     2262    2272    2269    2362
Hammersmith and Fulham                      1930    1837    1883    1967
Haringey                                    2216    1966    2116    2262
Harrow                                      1152    1037    1151    1176
Havering                                    1462    1342    1395    1393
Hillingdon                                  1888    2053    2145    1921
Hounslow                                    1874    1996    2045    2169
Islington                                   2058    2056    2324    2509
Kensington and Chelsea                      1967    1521    1547    1824
Kingston upon Thames                         857     896    1033     983
Lambeth                                     3080    3038    3107    3142
Lewisham                                    2423    2166    2327    2254
London Heathrow and London City Airports     295     256     232     254
Merton                                      1123    1028    1268    1224
Newham                                      2665    2550    2699    2556
Redbridge                                   1982    1865    2194    2116
Richmond upon Thames                        1004     982    1013     960
Southwark                                   2899    2715    3107    2896
Sutton                                       976     888     931     916
Tower Hamlets                               2613    2264    2331    2406
Waltham Forest                              2180    1816    2043    2074
Wandsworth                                  1924    1868    2040    1989
Westminster                                 4977    4882    5643    5591

                                          201112  201201  201202  201203  \
Area
Barking and Dagenham                        1438    1529    1396    1672
Barnet                                      2026    1987    2033    2392
Bexley                                       857     971     925    1147
Brent                                       2438    2632    2352    2613
Bromley                                     1875    1827    1674    1815
Camden                                      2754    2720    2505    3065
Croydon                                     2302    3151    2360    2823
Ealing                                      2371    2698    2323    2775
Enfield                                     1625    1628    1773    2082
Greenwich                                   1872    1806    1606    1835
Hackney                                     1880    2315    2066    2677
Hammersmith and Fulham                      1899    1787    1757    1938
Haringey                                    2144    2137    1947    2385
Harrow                                      1173    1219    1110    1317
Havering                                    1327    1361    1426    1597
Hillingdon                                  2013    2014    1715    2027
Hounslow                                    1772    2216    1852    2186
Islington                                   1969    2085    1941    2473
Kensington and Chelsea                      1742    1744    1530    1882
Kingston upon Thames                         963     940     862     961
Lambeth                                     2812    3361    2445    3235
Lewisham                                    2046    2162    1908    2380
London Heathrow and London City Airports     246     214     227     208
Merton                                      1085    1073    1131    1235
Newham                                      2261    2478    2410    3094
Redbridge                                   1780    1985    1768    2075
Richmond upon Thames                         932     907     855    1064
Southwark                                   2791    2663    2595    2904
Sutton                                       896     877     905    1043
Tower Hamlets                               2120    2296    2237    2455
Waltham Forest                              1867    1778    1775    2160
Wandsworth                                  1956    1979    2022    2507
Westminster                                 5601    5386    4716    5824

                                          201204  201205  ...  201503  201504  \
Area                                                      ...
Barking and Dagenham                        1359    1495  ...    1543    1342
Barnet                                      2092    2132  ...    1969    1922
Bexley                                       981    1160  ...    1066     917
Brent                                       2216    2389  ...    2152    2014
Bromley                                     1515    1724  ...    1791    1724
Camden                                      2740    3151  ...    2601    2514
Croydon                                     2560    2810  ...    2622    2394
Ealing                                      2381    2698  ...    2203    2105
Enfield                                     1800    2018  ...    1940    1764
Greenwich                                   1664    1925  ...    1817    1737
Hackney                                     2344    2481  ...    2340    2211
Hammersmith and Fulham                      1873    2022  ...    1756    1706
Haringey                                    1992    2295  ...    2149    2063
Harrow                                      1053    1174  ...    1058     983
Havering                                    1332    1437  ...    1332    1200
Hillingdon                                  1815    1842  ...    1837    1730
Hounslow                                    1971    2017  ...    1759    1626
Islington                                   2345    2516  ...    2470    2381
Kensington and Chelsea                      1719    1796  ...    1615    1470
Kingston upon Thames                         835     861  ...     822     777
Lambeth                                     2906    2905  ...    2848    2769
Lewisham                                    1946    2170  ...    1985    1971
London Heathrow and London City Airports     206     208  ...     244     223
Merton                                      1085    1219  ...     996     970
Newham                                      2578    2770  ...    2650    2235
Redbridge                                   1741    1943  ...    1699    1504
Richmond upon Thames                         978    1205  ...     938     893
Southwark                                   2408    2922  ...    2506    2469
Sutton                                       930     994  ...     982     930
Tower Hamlets                               2221    2398  ...    2358    2135
Waltham Forest                              2060    2194  ...    1854    1732
Wandsworth                                  2087    2234  ...    2022    1886
Westminster                                 4922    5432  ...    4084    3879

                                          201505  201506  201507  201508  \
Area
Barking and Dagenham                        1495    1440    1584    1409
Barnet                                      1960    2105    2192    2011
Bexley                                      1088    1052    1029     873
Brent                                       2189    2141    2052    1998
Bromley                                     1777    1825    1809    1744
Camden                                      2799    2659    2576    2306
Croydon                                     2609    2670    2473    2320
Ealing                                      2425    2435    2380    2167
Enfield                                     1909    1851    2046    1894
Greenwich                                   1847    1788    1888    1789
Hackney                                     2430    2492    2461    2234
Hammersmith and Fulham                      1778    1658    1729    1601
Haringey                                    2009    2075    2320    2153
Harrow                                      1142    1044     961    1041
Havering                                    1276    1426    1471    1332
Hillingdon                                  1832    1921    1787    1709
Hounslow                                    1823    1851    1979    1752
Islington                                   2492    2396    2397    2215
Kensington and Chelsea                      1636    1632    1647    1744
Kingston upon Thames                         845     891     862     814
Lambeth                                     3009    2837    3081    3063
Lewisham                                    2111    2105    2122    2037
London Heathrow and London City Airports     267     272     303     278
Merton                                      1127    1054    1153    1063
Newham                                      2420    2590    2710    2447
Redbridge                                   1515    1744    1656    1478
Richmond upon Thames                         996     892     889     907
Southwark                                   2862    2689    2672    2618
Sutton                                       867    1022     838     871
Tower Hamlets                               2481    2358    2719    2411
Waltham Forest                              1681    1934    1958    1804
Wandsworth                                  2056    1978    1973    1833
Westminster                                 4165    3926    4067    4094

                                          2011/2012  2012/2013  2013/2014  \
Area
Barking and Dagenham                          17743      16954      15935
Barnet                                        25481      24275      22752
Bexley                                        12075      11904      12163
Brent                                         29525      25710      24927
Bromley                                       21103      19841      19845
Camden                                        34651      30985      27569
Croydon                                       32361      29896      27701
Ealing                                        31035      28602      25394
Enfield                                       22272      22312      22523
Greenwich                                     21717      20139      20191
Hackney                                       27860      27117      25244
Hammersmith and Fulham                        22658      20194      19057
Haringey                                      25765      22004      22508
Harrow                                        13964      12823      12154
Havering                                      16755      16024      14911
Hillingdon                                    22875      19775      20241
Hounslow                                      24159      20913      19876
Islington                                     27136      26101      24706
Kensington and Chelsea                        20649      19666      18120
Kingston upon Thames                          10873       9873       9246
Lambeth                                       36061      33976      32705
Lewisham                                      26079      23863      21950
London Heathrow and London City Airports       2806       2655       2755
Merton                                        13753      12918      11290
Newham                                        31615      30213      28822
Redbridge                                     23130      21481      20078
Richmond upon Thames                          11890      11225      10464
Southwark                                     33656      32384      30183
Sutton                                        11289      10750      10461
Tower Hamlets                                 28799      28570      26494
Waltham Forest                                24154      23271      21627
Wandsworth                                    25046      24336      21678
Westminster                                   64050      59040      51027

                                          2014/2015
Area
Barking and Dagenham                          16750
Barnet                                        23736
Bexley                                        12160
Brent                                         24757
Bromley                                       20755
Camden                                        29865
Croydon                                       29752
Ealing                                        26552
Enfield                                       22400
Greenwich                                     21057
Hackney                                       26902
Hammersmith and Fulham                        20438
Haringey                                      24529
Harrow                                        12434
Havering                                      15841
Hillingdon                                    21861
Hounslow                                      21210
Islington                                     27556
Kensington and Chelsea                        19252
Kingston upon Thames                          10087
Lambeth                                       33836
Lewisham                                      23048
London Heathrow and London City Airports       3017
Merton                                        12542
Newham                                        29411
Redbridge                                     19777
Richmond upon Thames                          10783
Southwark                                     31001
Sutton                                        11099
Tower Hamlets                                 27885
Waltham Forest                                20980
Wandsworth                                    23177
Westminster                                   48518

[33 rows x 53 columns]

In [ ]:
new_data = crime_data.groupby('Area')['2011/2012','2012/2013','2013/2014','2014/2015'].sum().reset_index()
new_data

<ipython-input-15-9f1d2c3baa63>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  new_data = crime_data.groupby('Area')['2011/2012','2012/2013','2013/2014','2014/2015'].sum().reset_index()

,Area,2011/2012,2012/2013,2013/2014,2014/2015
0,Barking and Dagenham,17743,16954,15935,16750
1,Barnet,25481,24275,22752,23736
2,Bexley,12075,11904,12163,12160
3,Brent,29525,25710,24927,24757
4,Bromley,21103,19841,19845,20755
5,Camden,34651,30985,27569,29865
6,Croydon,32361,29896,27701,29752
7,Ealing,31035,28602,25394,26552
8,Enfield,22272,22312,22523,22400
9,Greenwich,21717,20139,20191,21057
10,Hackney,27860,27117,25244,26902
11,Hammersmith and Fulham,22658,20194,19057,20438
12,Haringey,25765,22004,22508,24529
13,Harrow,13964,12823,12154,12434
14,Havering,16755,16024,14911,15841
15,Hillingdon,22875,19775,20241,21861
16,Hounslow,24159,20913,19876,21210
17,Islington,27136,26101,24706,27556
18,Kensington and Chelsea,20649,19666,18120,19252
19,Kingston upon Thames,10873,9873,9246,10087
20,Lambeth,36061,33976,32705,33836
21,Lewisham,26079,23863,21950,23048
22,London Heathrow and London City Airports,2806,2655,2755,3017
23,Merton,13753,12918,11290,12542
24,Newham,31615,30213,28822,29411
25,Redbridge,23130,21481,20078,19777
26,Richmond upon Thames,11890,11225,10464,10783
27,Southwark,33656,32384,30183,31001
28,Sutton,11289,10750,10461,11099
29,Tower Hamlets,28799,28570,26494,27885
30,Waltham Forest,24154,23271,21627,20980
31,Wandsworth,25046,24336,21678,23177
32,Westminster,64050,59040,51027,48518

In [ ]:
from google.colab import files
uploaded=files.upload()
! pip install pandas
import pandas as pd
df = pd.read_excel("residence earning.xlsx")
df.dropna(how='all', inplace=True)
pd.set_option('display.max_columns', None)
df.drop(df.index[0])
df.drop(df.index[34:52], inplace=True)
df.columns
clean = df.drop([2002,  'Unnamed: 3',
                2003,  'Unnamed: 5',          2004,  'Unnamed: 7',
                2005,  'Unnamed: 9',          2006, 'Unnamed: 11',
                2007, 'Unnamed: 13',          2008, 'Unnamed: 15',
                2009, 'Unnamed: 17',          2010, 'Unnamed: 19',
         'Unnamed: 21','Unnamed: 23','Unnamed: 25','Unnamed: 27','Unnamed: 29',
          2016, 'Unnamed: 31',
                2017, 'Unnamed: 33',          2018, 'Unnamed: 35',
                2019, 'Unnamed: 37',          2020, 'Unnamed: 39',
                2021, 'Unnamed: 41',          2022, 'Unnamed: 43'], axis=1)

for year in range(2011,2016):
  clean[year] = pd.to_numeric(clean[year], errors='coerce')
clean['income 2011/2012'] = clean[[2011, 2012]].mean(axis=1, numeric_only=True)
clean['income 2012/2013'] = clean[[2012, 2013]].mean(axis=1, numeric_only=True)
clean['income 2013/2014'] = clean[[2013, 2014]].mean(axis=1, numeric_only=True)
clean['income 2014/2015'] = clean[[2014, 2015]].mean(axis=1, numeric_only=True)
cleaned_income= clean.groupby('Area')['income 2011/2012','income 2012/2013','income 2013/2014','income 2014/2015'].mean().reset_index()
cleaned_income

Saving residence earning.xlsx to residence earning.xlsx
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

<ipython-input-16-e15bd4cdeb1d>:28: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  cleaned_income= clean.groupby('Area')['income 2011/2012','income 2012/2013','income 2013/2014','income 2014/2015'].mean().reset_index()

,Area,income 2011/2012,income 2012/2013,income 2013/2014,income 2014/2015
0,Barking and Dagenham,451.05,445.60,431.85,429.55
1,Barnet,500.70,510.30,498.30,485.05
2,Bexley,507.10,503.50,505.25,501.85
3,Brent,428.45,441.90,441.80,449.70
4,Bromley,559.15,573.85,579.80,581.15
5,Camden,612.00,620.75,621.30,600.60
6,City of London,NaN,NaN,NaN,NaN
7,Croydon,487.45,487.30,490.20,495.60
8,Ealing,490.80,498.55,500.25,497.05
9,Enfield,465.60,452.85,456.55,468.20
10,Greenwich,479.25,493.50,512.80,520.80
11,Hackney,514.40,515.20,516.00,523.75
12,Hammersmith and Fulham,603.70,612.00,610.30,628.30
13,Haringey,480.45,476.85,466.15,483.85
14,Harrow,479.70,475.30,485.60,498.70
15,Havering,503.10,495.30,494.40,508.30
16,Hillingdon,503.55,515.95,507.35,495.65
17,Hounslow,476.15,479.10,471.30,479.55
18,Islington,601.80,605.55,609.75,608.60
19,Kensington and Chelsea,724.45,690.85,684.00,636.85
20,Kingston upon Thames,590.45,602.65,580.35,565.55
21,Lambeth,555.75,555.70,541.80,544.95
22,Lewisham,486.40,512.55,522.00,518.00
23,Merton,537.65,532.70,534.95,545.50
24,Newham,376.15,378.70,390.65,407.65
25,Redbridge,503.10,515.30,510.75,525.35
26,Richmond upon Thames,667.90,670.65,662.35,651.10
27,Southwark,533.55,530.50,526.70,543.00
28,Sutton,507.70,517.75,513.15,503.30
29,Tower Hamlets,554.55,570.95,575.00,564.90
30,Waltham Forest,468.50,457.20,443.30,460.55
31,Wandsworth,641.95,638.20,652.60,665.60
32,Westminster,685.90,663.00,642.30,657.80

In [ ]:
dfs = [life_satisfaction, life_anxiety, gcse_df, crime]
merged_df = dfs[0]

for df in dfs[1:]:
    merged_df = pd.merge(merged_df, df, on='Area')
merged_df

,Area,Life Satisifaction 2011/2012,Life Satisfaction 2012/2013,Life Satisfaction 2013/2014,Life Satisfaction 2014/2015,Anxiety 2011/2012,Anxiety 2012/2013,Anxiety 2013/2014,Anxiety 2014/2015,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs 2011/12,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs 2012/13,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs 2013/2014,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C including English & mathematics GCSEs 2014/2015,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades 2011/2012\t,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades 2012/2013,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades\t2013/2014,Percentage of pupils at the end of key stage 4 achieving 5+ A*-C grades 2014/2015,MajorText,MinorText,201108,201109,201110,201111,201112,201201,201202,201203,201204,201205,201206,201207,201208,201209,201210,201211,201212,201301,201302,201303,201304,201305,201306,201307,201308,201309,201310,201311,201312,201401,201402,201403,201404,201405,201406,201407,201408,201409,201410,201411,201412,201501,201502,201503,201504,201505,201506,201507,201508
0,Barking and Dagenham,7.05,7.09,7.01,7.32,3.23,3.27,3.39,3.15,58.6,60.2,58.2,54,83.3,82.5,65.5,66.4,Arson and Criminal Damage,Arson,17,6,15,13,5,10,4,9,4,8,6,4,8,9,6,3,4,2,4,5,7,3,3,6,2,1,5,8,6,5,2,1,5,7,3,6,11,5,5,10,5,3,3,10,5,8,5,11,9
1,Barking and Dagenham,7.05,7.09,7.01,7.32,3.23,3.27,3.39,3.15,58.6,60.2,58.2,54,83.3,82.5,65.5,66.4,Arson and Criminal Damage,Criminal Damage,193,149,137,150,161,136,113,174,132,153,156,135,126,140,101,117,130,138,134,119,118,112,128,131,139,126,130,139,136,126,130,136,115,127,127,137,157,126,142,117,113,117,113,143,132,170,130,162,130
2,Barking and Dagenham,7.05,7.09,7.01,7.32,3.23,3.27,3.39,3.15,58.6,60.2,58.2,54,83.3,82.5,65.5,66.4,Burglary,Burglary Business and Community,99,66,65,64,53,46,43,64,62,51,70,50,46,37,47,68,81,68,68,57,33,39,33,41,50,49,47,50,39,53,55,47,47,48,42,50,46,33,45,42,33,21,28,40,42,41,26,42,56
3,Barking and Dagenham,7.05,7.09,7.01,7.32,3.23,3.27,3.39,3.15,58.6,60.2,58.2,54,83.3,82.5,65.5,66.4,Burglary,Domestic Burglary,97,98,136,167,181,184,149,195,152,131,114,129,112,132,145,187,165,197,185,186,151,137,112,118,98,83,144,151,107,112,114,144,83,90,89,105,113,96,110,180,133,161,110,129,65,61,68,89,89
4,Barking and Dagenham,7.05,7.09,7.01,7.32,3.23,3.27,3.39,3.15,58.6,60.2,58.2,54,83.3,82.5,65.5,66.4,Drug Offences,Drug Trafficking,10,5,2,13,3,6,6,6,10,5,3,3,7,5,9,9,7,2,6,8,7,6,7,5,6,5,9,4,4,8,16,10,3,9,6,6,9,4,8,8,2,2,5,5,3,5,8,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1673,Westminster,7.33,7,7.53,7.45,3.52,3.66,3.13,3.38,69.9,69.6,68.1,67.5,87.5,86.8,76.8,77.5,Vehicle Offences,Theft from a Motor Vehicle,156,213,198,234,182,176,129,236,216,262,209,235,206,192,184,199,227,233,264,215,206,244,215,233,185,202,293,236,204,196,227,267,169,200,150,140,124,175,173,185,201,177,152,170,137,152,159,193,158
1674,Westminster,7.33,7,7.53,7.45,3.52,3.66,3.13,3.38,69.9,69.6,68.1,67.5,87.5,86.8,76.8,77.5,Vehicle Offences,Theft or Taking of a Motor Vehicle,38,41,38,35,33,52,19,41,60,77,49,51,47,58,50,49,29,39,42,42,56,49,57,67,57,56,53,73,51,62,72,61,58,70,89,71,45,73,79,68,50,72,58,71,72,91,88,64,68
1675,Westminster,7.33,7,7.53,7.45,3.52,3.66,3.13,3.38,69.9,69.6,68.1,67.5,87.5,86.8,76.8,77.5,Violence Against the Person,Homicide,0,0,0,0,1,0,0,0,1,0,2,0,1,0,0,0,0,1,0,3,0,0,0,0,0,0,0,0,2,0,2,0,0,1,0,0,0,0,0,0,2,1,2,0,0,0,0,0,0
1676,Westminster,7.33,7,7.53,7.45,3.52,3.66,3.13,3.38,69.9,69.6,68.1,67.5,87.5,86.8,76.8,77.5,Violence Against the Person,Violence with Injury,244,293,328,315,306,271,211,203,226,247,225,242,271,268,224,236,236,238,177,244,221,231,258,209,217,209,238,216,280,246,210,280,257,254,282,276,289,310,290,259,295,255,247,281,265,291,280,275,292
1677,Westminster,7.33,7,7.53,7.45,3.52,3.66,3.13,3.38,69.9,69.6,68.1,67.5,87.5,86.8,76.8,77.5,Violence Against the Person,Violence without Injury,236,248,305,310,300,271,287,306,244,258,230,238,266,230,264,252,248,220,166,250,203,243,246,264,250,247,248,264,274,268,270,291,250,274,321,336,329,330,339,360,325,314,379,364,314,393,401,396,416